---
title: "Unit 2 Task 3: Longevity of Players"
date: 2025-04-02T11:02:05+06:00
lastmod: 2025-04-02T10:42:26+06:00
weight: 4
draft: false
# search related keywords
keywords: [""]
---

### Background

How do you know if you have correctly programmed a query or an analysis? The process of confirming that your analysis or dataset is "correct" is called validation. 

Imagine you are new on the job and received the assignment to run queries on a baseball dataset. Confirming you did things correctly is a good idea before presenting your data to others and letting them discover your mistake. Or maybe, it isn't a matter of you doing something wrong as just a realization that the data source is flawed. Making that discovery is very important and makes you look really good; as opposed to someone else discovering it later - which can be a big hit to your credibility.

Consider all the various ways you might want to validate the query results. One way to validate, though certainly not the only way and not necessarily the best way, is to try to accomplish the same task in a different system or language. That's the purpose of this assignment.


### Client Request

For this project, you will validate the assignments you have done previously, but this time using Python pandas code. You will still need to connect to the database to pull the data in, but all the filtering, calculating, joining, etc. should be done with Python pandas (or polars). 


### Data

::: {.callout-note collapse="false"}
This project will use the Lahman Baseball Database. In order to complete this project, you will need to download the database and save it inside the DS250 folder (hopefully you have a folder dedicated to this class) next to the .qmd file you will be using for this assignment. Note: Right click the __'Download'__ link and select "Save Link As" to download the data to your computer.
:::

__Download:__ [lahmansbaseballdb](/Data/lahmansbaseballdb.sqlite)  
__Information:__ [Lahman Data Dictionary](/Data/readme2014.txt)  
__Setup Instructions:__ [See SQL Setup](/Setup/sql_setup.qmd)


### Readings

::: {.callout-note collapse="true"}
Complete these readings before we cover the material in class. This will help you retain the material and make the class period more engaging - not less. 

In other words, if an assignment is due on Wednesday, we will cover the material needed to complete the assignment on Tuesday. Therefore, you should complete the readings on Monday (or anytime before class on Tuesday).
:::

There are many [flavors of SQL](https://en.wikipedia.org/wiki/Database#Database_management_system) but most flavors have the same base commands. SQL queries are typed in the following pattern;

```SQL
SELECT -- <columns> and <column calculations>
FROM -- <table name>
  JOIN -- <table name>
  ON -- <columns to join>
WHERE -- <filter condition on rows>
GROUP BY -- <subsets for column calculations>
HAVING -- <filter conditions on groups>
ORDER BY -- <how the output is returned in sequence>
LIMIT -- <number of rows to return>
```

Reading you may find useful (depending on how you approach the assignment):
   
- [Inline subqueries](https://docs.data.world/documentation/sql/concepts/advanced/inline_subqueries.html)
- [Dates/Times in SQLite](https://www.sqlite.org/lang_datefunc.html)

### Questions and Tasks

Download the [Unit 2 Task 3 Template](../Templates/unit2_task3_template.qmd).

1. __Write an SQL query that pulls in the batting average table. Then, with Python Pandas code create a dataframe that contains playerID, yearID, and batting average for players with at least 10 at bat that year. Sort the dataframe from highest batting average to lowest, and then by playerid alphabetically. Show the top 5 results in your report.__

1. __Now use Python Pandas to calculate the batting average for players over their entire careers (all years combined). Only include players with at least 100 at bats over their entire career, and print the top 5 results.__

1. __Write an SQL query that pulls in the the salaries table and the schools table (and any other tables you might need) and store them in pandas dataframes. Combine the dataframes to create a list of baseball players who attended BYU-Idaho. The new table should contain five columns: playerID, schoolID, salary, and the yearID/teamID associated with each salary. Order the table by salary (highest to lowest) and print out the table in your report.__

1. __Pick any two baseball teams and compare them using a metric of your choice (average salary, home runs, number of wins, etc). Be creative! Write an SQL query to read in the tables you need, then use pandas to manipulate the data. Finally, make a graph using Lets-Plot to visualize the comparison. What do you learn?__


### Submission:
::: {.callout-note collapse="true"}
When you have completed the report, you will need to follow this process to submit your work:

1. Have this assignment's template/quarto file open in VS Code and nothing else
1. Click `Preview Button` in VS Code in the top right of the screen
    a. This will render the project but also entire course work portfolio into `HTML` files for review
    b. Confirm everything displas as you would like it to
    c. How you see it will be how it is viewed for grading
    d. If there is an error in any cell of the quarto files, the rendering will stop and you will need to fix the error before rendering again (if you get stuck post your error in Slack)
1. Once the report is confirmed close the preview and open a VS Code `Terminal`
    a. click `Terminal` in the top menu bar and then `New Terminal`
1. Type the following in the terminal `quarto render `
    a. Then drag and drop this assignment into the terminal. This will add the file path to the terminal command
    a. Press Enter
1. This will render the project into a `HTML` file in the same location as the `.qmd` file
1. To locate the file in VS Code
    a. Right click on the file in the file explorer and select `Reveal in File Explorer`(Win) or `Reveal in Finder`(Mac)
1. Upload `HTML` file into Canvas
:::


### Deliverables:

_Use this [unit2_task3_template](../Templates/unit2_task3_template.qmd) to submit your Client Report._

Answers to the questions | tasks. Each should include a written description of your results, code cells with comments, charts and/or tables.


::: {.callout-note collapse="false"}
_Your report should be written in quarto markdown files and rendered to an HTML File. Upload the HTML file in Canvas. (Do not submit the `.qmd` file)_  
:::