---
title: "Unit 2 Task 4: Highest Paid Positions"
date: 2025-04-02T11:02:05+06:00
lastmod: 2025-04-02T10:42:26+06:00
weight: 4
draft: false
# search related keywords
keywords: [""]
---

### Background

When you hear the word “relationship” what is the first thing that comes to mind? Probably not baseball. But a relationship is simply a way to describe how two or more objects are connected. There are many relationships in baseball such as those between teams and managers, players and salaries, even stadiums and concession prices. 

The graphs on [Data Visualizations from Best Tickets](https://web.archive.org/web/20200804101201/http://www.besttickets.com/blog/mlb-players-census/) show many other relationships that exist in baseball.


### Client Request

For this project, the Client wants SQL queries that they can use to retrieve data for use on their website without needing Python. They would also like to see the results in Lets-Plot charts.


### Data

::: {.callout-note collapse="false"}
Every data science project should start with data, and our class projects are no different. Each project will have __'URL'__ and __'Information'__ links like the ones below. Project 3 will use the Lahman Baseball Database. You will need to download the database and set it up on your computer to complete the project. Place it inside the DS250 folder (hopefully you have a folder dedicated to this class) next to the .qmd file you will be using for this assignment. Note: Right click the __'Download'__ link and select "Save Link As" to download the data to your computer.
:::

__Download:__ [lahmansbaseballdb](/Data/lahmansbaseballdb.sqlite)  
__Information:__ [Lahman Data Dictionary](/Data/readme2014.txt)  
__Setup Instructions:__ [See SQL Setup](/Setup/sql_setup.qmd)


### Readings

::: {.callout-note collapse="true"}
Complete these readings before we cover the material in class. This will help you retain the material and make the class period more engaging - not less. 

In other words, if an assignment is due on Wednesday, we will cover the material needed to complete the assignment on Tuesday. Therefore, you should complete the readings on Monday (or anytime before class on Tuesday).
:::

There are many [flavors of SQL](https://en.wikipedia.org/wiki/Database#Database_management_system) but most flavors have the same base commands. SQL queries are typed in the following pattern;

```SQL
SELECT -- <columns> and <column calculations>
FROM -- <table name>
  JOIN -- <table name>
  ON -- <columns to join>
WHERE -- <filter condition on rows>
GROUP BY -- <subsets for column calculations>
HAVING -- <filter conditions on groups>
ORDER BY -- <how the output is returned in sequence>
LIMIT -- <number of rows to return>
```

Reading you may find useful (depending on how you approach the assignment):
   
- [Inline subqueries](https://docs.data.world/documentation/sql/concepts/advanced/inline_subqueries.html)
- [CASE](https://docs.data.world/documentation/sql/concepts/intermediate/CASE.html)
- [WITH](https://docs.data.world/documentation/sql/concepts/advanced/WITH.html)

### Question 1

- Write an SQL query that provides a summary table showing the average salary for each position (e.g., pitcher, catcher, outfielder). Position information can be found in the fielding table in the POS column.

Include the following columns:

    - position
    - average_salary
    - total_players
    - highest_salary

The highest_salary column should display the highest salary ever earned by a player in that position.

- Additionally, create a new column called salary_category using a case statement:

    - If the average salary is above $3 million, categorize it as “High Salary.”
    - If the average salary is between $2 million and $3 million, categorize it as “Medium Salary.”
    - Otherwise, categorize it as “Low Salary.”

- Order the table by average salary in descending order.

__Hint__: Beware, it is common for a player to play multiple positions in a single year. For this analysis, each player’s salary should only be counted toward one position in a given year: the position at which they played the most games that year. This will likely require a (sub-query)

### Submission:
::: {.callout-note collapse="true"}
When you have completed the report, you will need to follow this process to submit your work:

1. Have this assignment's template/quarto file open in VS Code and nothing else
1. Click `Preview Button` in VS Code in the top right of the screen
    a. This will render the project but also entire course work portfolio into `HTML` files for review
    b. Confirm everything displas as you would like it to
    c. How you see it will be how it is viewed for grading
    d. If there is an error in any cell of the quarto files, the rendering will stop and you will need to fix the error before rendering again (if you get stuck post your error in Slack)
1. Once the report is confirmed close the preview and open a VS Code `Terminal`
    a. click `Terminal` in the top menu bar and then `New Terminal`
1. Type the following in the terminal `quarto render `
    a. Then drag and drop this assignment into the terminal. This will add the file path to the terminal command
    a. Press Enter
1. This will render the project into a `HTML` file in the same location as the `.qmd` file
1. To locate the file in VS Code
    a. Right click on the file in the file explorer and select `Reveal in File Explorer`(Win) or `Reveal in Finder`(Mac)
1. Upload `HTML` file into Canvas
:::


### Deliverables:

No template is provided. Create a new quarto file for this assignment. It is part of stretching yourself. But don't forget to __include a 1 paragraph write-up / summary description of your results!__


::: {.callout-note collapse="false"}
_Your report should be written in quarto markdown files and rendered to an HTML File. Upload the HTML file in Canvas. (Do not submit the `.qmd` file)_  
:::